apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongostate
spec:
  serviceName: mongostate-headless
  replicas: 2
  selector:
    matchLabels:
      app: mongostate
  template:
    metadata:
      labels:
        app: mongostate
    spec:
      containers:
      - image: mongo:latest
        name: mongostate-container
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongostate
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongostate
        - name: MONGO_INITDB_ROOT_DATABASE
          value: mongostate	
        - name: TEST_PASSWORD
          value: testing
        volumeMounts:
        - name: mongostate-cfvol
          mountPath: /docker-entrypoint-initdb.d
        - name: mongostate-secvol
          mountPath: /etc/mongostate-secret
          readOnly: true
        args: [ "mongod", "--replSet", "RepSet", "--keyFile", "/etc/mongostate-secret/keyfile" ]
      volumes:
      - name: mongostate-cfvol
        configMap:
          name: mongostate-configmap
          defaultMode: 0755
      - name: mongostate-secvol
        secret:
          secretName: mongostate-secret
          defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: mongostate-headless
  labels:
    app: mongostate
spec:
  selector:
    app: mongostate
  ports:
  - name: service
    port: 27017
    protocol: TCP
    targetPort: 27017
  clusterIP: None
