apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongodb-init.sh: |
    #!/bin/bash
    mongod --bind_ip_all &
    mongosh <<EOF
    db = db.getSiblingDB('demo')
    db.createUser({
      user: 'demo',
      pwd: '$DEMO_PASSWORD',
      roles: [{ role: 'readWrite', db: 'demo' }],
    });
    db.createCollection('utlmap')
    EOF
