apiVersion: v1
kind: Secret
metadata:
  name: mongo-init-secret
type: Opaque
stringData:
  username: mongostate
  password: mongostate
  database: mongostate
  testpassword: testing
---
apiVersion: v1
kind: Secret
metadata:
  name: mongostate-secret
data:
  keyfile: T2xpUVA4QnFHaDArWjRZWmhFSzFBY2Nld1ZTQlBTZGI2UCtyNGNrT1Q2VWZoT2k0QXVwcytBSzczOTRqcFZxZQpzL1VxLyt5dXpIdEhSbmoxZDZvOWNpbkdVRGRDb1h5My9XaDBzV0o1ZXJYVlB4SDlFSllUOFhWOFlIMEVxS2dBCld6K0ZRTmN3S09YRkpKMDR4SGpkN2V4ckY2a1BTdVBWQkJTYUR2bmJqbWpQejYwQUNzNk5IdXVjUHB0Yjh1M3AKYzFSQmh5dmVoUFRqT1FGR1VQUnZPL1dXeFJuNHhZNmR1eWd3NmIxekhySVYwRlZ4enhkWkdNNCs1aDc0UmpFZgpoZDh1UXNveUdzRkNiOHRmYnZLSHdNN0tEOVdxZGNiSWNSU2NNL3pWUmFvZjVnRDI1bXFkZ1IrMHp5YlVvRkhoCm5VcCt5NU91WVNuNFI3Q2tLb0RSekdmM1NRQittbnJjRmg5Rmd2amlQMzZqOWtMVGp2WnJhMk9Nd2FkcytxaU8KLzdhRlllazk0V1JaRklkZnVoNGNTOUJOakZucWk2dlE1VjhBdkpWOWtZYTh2WFZFNytVd0Z2dnJ2M3VwYXZMago2UUVSVUZ4aEhLaFFFTlRPWTBjcThKenhkTGtmSTZIUkdnQldIOXdzMEN4THVTQWpyV3ZZMUdQUEJzM0JkaFloCjVoZUV2clRSS2ZxVHIybUJrbDVUdW1MRXVTNDJNaHVvQlpjNWFwRlR5cnJUdFZDVkdWRWhPS3pmaFpzZlUwSmkKMXBGaG1mNThQVEI0Ukp2bVhxVngyOVZJNmtXanBXS2VFSTYwbDRIWEU1UzBLRlAra25BYzNoYzdEQjcyMVRTcQpzV1ZZY1lSL21veFZYS3FjS3pnY2pNUHl2Z1hjY3I5bUc3Zk9xa0FJZW1FZmRrcUpVelBmTmRUOHFGeFNlSDdBCnBMZDFPK0Jma28xQVdiendRaXNSUERTRHpxU3E1blB0bGRySERhaExwajc4YlVPSDhBMXkxeGUzcHVWMFBJcUUKM1E0UEZCVkNHTTI3d3R3aVN5d2lrbzJabmY5d3BZSEExSUNtVjhldU5HdVg2cWJnZVZ1RzVkVXhQYmVJZGdwcgpqNStGSWsrTXJkbGpyaUMyL05QL0MyWEVkM2JieEU4SkJQM2pkdndBOGRXcDVTaWhSeWYzQ1Ezc01ZZGM3cWNnCmMvY0xXUkdHZnZ4d0o5TEx6OVBIaEdBTnpaamZLdWhwTVVmSTU5Sk53MjR3cVdvNVdPdm5kanJsVzJoSWsra2cKVm9jdEw2eVN2M1Rkd2p1M0FMV1hIaVV3ZG01WQo=
type: Opaque
