apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongodb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongodb
        - name: MONGO_INITDB_ROOT_DATABASE
          value: mongodb	
        - name: DEMO_PASSWORD
          value: demo
        command: ["/bin/bash"]
        args: ["-c", "mongo --bind_ip_all && /docker-entrypoint-initdb.d/mongo-init.sh"]
        volumeMounts:
        - name: mongo-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mongo-initdb
        configMap:
          name: mongo-initdb
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - name: service
    port: 27017
    protocol: TCP
    targetPort: 27017
  type: LoadBalancer
