apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodemo
  template:
    metadata:
      labels:
        app: mongodemo
    spec:
      containers:
      - image: mongo:latest
        name: mongodemo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongodemo
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongodemo
        - name: MONGO_INITDB_ROOT_DATABASE
          value: mongodemo	
        - name: DEMO_PASSWORD
          value: demo
        volumeMounts:
        - name: mongodb-cfvol
          mountPath: /docker-entrypoint-initdb.d
        command: ["/bin/sh"]
        args:
        - "-c"
        - |
            cp mongod --fork --sylog --bind_ip_all &&
            /docker-entrypoint-initdb.d/mongo-init.sh
      volumes:
      - name: mongodb-cfvol
        configMap:
          name: mongodb-configmap
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: mongodemo-service
  labels:
    app: mongodemo
spec:
  selector:
    app: mongodemo
  ports:
  - name: service
    port: 27017
    protocol: TCP
    targetPort: 27017
  type: LoadBalancer
