apiVersion: v1
kind: ConfigMap
metadata:
  name: mongostate-configmap
data:
  mongostate-init.sh: |
    #!/bin/bash
    set +e
    if [ "${HOSTNAME}" == "mongostate-0" ]
    then
      mongosh <<EOF
      db.grantRolesToUser(
        "admin",
        [ "clusterManager" ]
      )
      rs.initiate({ '_id': "RepSet", 'members':[ { '_id': 0, 'host': "mongostate-0.mongostate-headless.default.svc.cluster.local:27017" } ]})
      rs.add("mongostate-1.mongostate-headless.default.svc.cluster.local:27017")   
      db = db.getSiblingDB('statetest')
      db.createUser({
        user: 'tester',
        pwd: '$TEST_PASSWORD',
        roles: [{ role: 'readWrite', db: 'testing' }],
      });
      db.createCollection('urlmap')
    EOF
    fi
