apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongostate
spec:
  serviceName: mongostate-headless
  replicas: 2
  selector:
    matchLabels:
      app: mongostate
  template:
    metadata:
      labels:
        app: mongostate
    spec:
      initContainers:
      - name: keyfile-prep
        image: busybox
        volumeMounts:
        - name: mongostate-secvol
          mountPath: /etc/mongosecret
        command: ["/bin/sh"]
        args:
        - -c
        - |
            mkdir -p /var/mangosecret &&
            cp /etc/mongosecret/keyfile /var/mangosecret/keyfile &&
            chmod 400 /var/mangosecret/keyfile &&
            chown 999:999 /var/mangosecret/keyfile && 
            sleep 5
      containers:
      - image: mongo:latest
        name: mongostate-container
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongostate
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongostate
        - name: MONGO_INITDB_ROOT_DATABASE
          value: mongostate	
        - name: TEST_PASSWORD
          value: testing
        volumeMounts:
        - name: mongostate-cfvol
          mountPath: /docker-entrypoint-initdb.d
        args: [ "mongod", "--replSet", "RepSet", "--keyFile", "/var/mangosecret/keyfile" ]
      volumes:
      - name: mongostate-cfvol
        configMap:
          name: mongostate-configmap
          defaultMode: 0755
      - name: mongostate-secvol
        secret:
          secretName: mongostate-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongostate-headless
  labels:
    app: mongostate
spec:
  selector:
    app: mongostate
  ports:
  - name: service
    port: 27017
    protocol: TCP
    targetPort: 27017
  clusterIP: None
