apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodemo
  template:
    metadata:
      labels:
        app: mongodemo
    spec:
      containers:
      - image: snpsuen/mongodemo:v1
        name: mongodemo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongodemo
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongodemo
        - name: MONGO_INITDB_ROOT_DATABASE
          value: mongodemo
        - name: DEMO_PASSWORD
          value: demo
        command:
        - mongod
        - "--bind_ip_all"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodemo-service
  labels:
    app: mongodemo
spec:
  selector:
    app: mongodemo
  ports:
  - name: service
    port: 27017
    protocol: TCP
    targetPort: 27017
  type: LoadBalancer
