apiVersion: v1
kind: ConfigMap
metadata:
  name: mongostate-configmap
data:
  mongostate-init.sh: |
    #!/bin/bash
    if [ "${HOSTNAME}" == "mongostate-0" ]
    then
      echo ">>> Check if mongod has started running  ...\n"
      echo "ps -aux | grep RepSet | grep bind_ip_all | grep -v grep ..."
      ps -aux | grep RepSet | grep bind_ip_all | grep -v grep
      while [ $? -ne 0 ]
      do
        echo "sleep 5 ..."
        sleep 5
        echo "ps -aux | grep RepSet | grep bind_ip_all | grep -v grep ..."
        ps -aux | grep RepSet | grep bind_ip_all | grep -v grep
      done
      echo ">>> mongod is running ...\n"
      mongosh <<EOF
      rs.initiate({ _id: "RepSet", members:[ { _id: 0, host: "mongostate-0.mongostate-headless:27017" } ]})
      rs.add("mongostate-1.mongostate-headless:27017")   
      db = db.getSiblingDB('testing')
      db.createUser({
        user: 'tester',
        pwd: '$TEST_PASSWORD',
        roles: [{ role: 'readWrite', db: 'testing' }],
      });
      db.createCollection('utlmap')
    EOF
    fi
